version: "3.9"
services:
  mobile:
    image: docker.io/library/eclipse-temurin:21-jdk
    working_dir: /app
    command: ["./mvnw","spring-boot:run","-Dspring-boot.run.profiles=dev"]
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
    volumes:
      - .:/app
      - maven_cache:/root/.m2
    depends_on:
      - db

  db:
    image: docker.io/library/postgres:13
    environment:
      POSTGRES_DB: mobile
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: docker.io/dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: huan@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgdata: {}
  pgadmin_data: {}
  maven_cache: {}